name: Build and push the beta docker images

on:
  push:
    branches:
      - main

jobs:
  build-docker-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        project: ['panel', 'node']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy types.ts instead of soft linking
        run: rm frontend/types.ts && cp backend/types.ts frontend/types.ts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push beta image for ${{ matrix.project }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.${{ matrix.project }}
          push: true
          tags: |
            ghcr.io/robin-sch/rstorage-${{ matrix.project }}:beta